### ISSUE TITLE
Import Person.

### ISSUE THREAD

**Issue by dkinzer** [jenkinslaw/crm#16]
This will involve importing company and member contacts first using the trick we came up with that adds N count to these person ids.

**Comment by bibliotechy** [comment]
@asather @dkinzer 
The current cdb includes 18 "Patron Types", some of which are duplicates. 
`Full Member Borrower
Full Member Non-Borrower
Jenkins Employee
Paralegal Student Non-Borrower
Special
Special
Undefined
Special
Non-Member
Firm Borrower
Undefined
Collection Development
Law School Student Non-Borrower
Deceased`

Do we want to bring this exact data over to the new CDB? Can the 3 specials be merged? What about undefined?

**Comment by ksnyder412** [comment]
While all specials are equal, some specials are more equal than others...
;0

K

On Wed, Sep 18, 2013 at 10:33 AM, Chad Nelson notifications@github.comwrote:

> @asather https://github.com/asather @dkinzerhttps://github.com/dkinzer
> The current cdb includes 18 "Patron Types", some of which are duplicates.
> Full Member Borrower
> Full Member Non-Borrower
> Jenkins Employee
> Paralegal Student Non-Borrower
> Special
> Special
> Undefined
> Special
> Non-Member
> Firm Borrower
> Undefined
> Collection Development
> Law School Student Non-Borrower
> Deceased
> 
> Do we want to bring this exact data over to the new CDB? Can the 3
> specials be merged? What about undefined?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jenkinslaw/cdb/issues/16#issuecomment-24668629
> .

## 

Ken Snyder
Network Administrator
Jenkins Law Library
833 Chestnut East, Suite 1220
Philadelphia, PA 19107
215-574-7916

**Comment by bibliotechy** [comment]
@ksnyder412 in Soviet Jenkins, customer databases you!

**Comment by bibliotechy** [comment]
This point is moot anyway. No customer records have been assigned there patron_types.

**Comment by asather** [comment]
You need to bring in at least these patron types:
![image](https://f.cloud.github.com/assets/460795/1166231/3d14fd24-2078-11e3-8868-0fd4c7da135c.png)

Patron types not listed in that screenshot can probably be ignored, so long as no customers are assigned to that patron type.
